config/routes.rb
RoomSessiom::Application.routes.draw do
  resources :rooms do 
    resources :sessions
  end

  root 'rooms#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, :presence => true
  has_many :sessions
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name))
    if @room.save
      redirect_to @room, notice: 'Room created'
    else
      render 'new'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def update
  end

  def show
    @room = Room.find(params[:id])
    @room_sessions = @room.sessions.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :find_room, only: [:new, :create]

  def index
    @sessions = Session.all
  end

  def new
    @session = @room.sessions.new
  end

  def create
    @session = @room.sessions.new(params.require(:session).permit(:begin_time, :end_time))
    if @session.save
      redirect_to @room, notice: 'Session for room created'
    else
      render 'new'
    end
  end

  def destroy
    @session = Session.find(params[:id])
    @session.destroy
    redirect_to sessions_path
  end

  def update
  end

  def show
    @session = Session.find(params[:id])
  end

  private
  def find_room
    @room = Room.find params[:room_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title= @title
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-default
      .container
        %button.navbar-toggle{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Room Sessions 
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Rooms', rooms_path
            -#%li= link_to 'Sessions', room_sessions_path
    .container
      .row
        #flash_errors.text-error
          = content_tag(:div, flash[:error], :id => "flash_error") if flash[:error]
          = content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert]
      .row
        .com-md-8.col-md-offset-1
          = yield
    -#= copyright

app/views/rooms/index.html.haml
!!!
%table.table.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th Room ID
      %th Room name
  - @rooms.each do |room|
    %tr
      %td= room.id
      %td= room.name
      %td= link_to "Create session", new_room_session_path(room) 
      %td= link_to "Destroy!", room, method: :delete 
= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
= form_for (@room) do |room|
  -#= room.error_messages
  %p
    = room.label "Room name"
    = room.text_field :name
    = room.submit :class => "btn"

app/views/rooms/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @room.name
%table.table.table-striped.table-bordered.table-condensed
  - @room_sessions.each do |rs|
    %tr
      %td= rs.id
      %td= rs.begin_time
      %td= rs.end_time